server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.61.10:7001/springhexo?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC # first need update
    username: root  # first need update
    password: 123456  # first need update
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: MyHikariPool
mybatis:
  type-aliases-package: pers.fulsun.hexoadmin.db.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true


jwt:
  token-validity: 60000 # token有效期，单位：毫秒
  secret-key: 9MQjIiLJmRLvQH+f6iSHKhgHybC6v3YAAq/AHWAxYlA= # 密钥
